export interface Product {
  id: number | string;
  slug: string;
  name: string;
  price: string;
  rawPrice: number;
  image: string;
  gallery?: string[];
  category: string;
  categorySlug: string;
  badge?: string;
  isNew?: boolean;
  description?: string;
  details?: string[];
  sizes?: string[];
  colors?: string[];
  fabric?: string;
}

export interface CategoryInfo {
  name: string;
  slug: string;
  description: string;
  bannerImage: string;
}

export const CATEGORIES: CategoryInfo[] = [
  {
    name: 'Gowns',
    slug: 'gowns',
    description: 'Breathtaking evening gowns, Aso-Ebi masterpieces, and statement silhouettes tailored with timeless Nigerian elegance.',
    bannerImage: '/assets/images/gowns/gown1.jpeg',
  },
  {
    name: 'Shoes',
    slug: 'shoes',
    description: 'Handcrafted luxury heels, stylish pointed mules, and premium footwear designed for comfort and confidence.',
    bannerImage: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Sandals',
    slug: 'sandals',
    description: 'Chic strappy sandals, crystal-embellished flats, and versatile day-to-evening footwear.',
    bannerImage: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Slippers',
    slug: 'slippers',
    description: 'Luxurious slide slippers, plush velvet house mules, and artisanal casual flats for everyday refinement.',
    bannerImage: 'https://images.unsplash.com/photo-1588661661153-dfbc227582b6?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Handbags',
    slug: 'handbags',
    description: 'Structured leather totes, elegant evening clutches, and minimalist crossbodies made from genuine leather.',
    bannerImage: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Clothes (Skirts & Blouses)',
    slug: 'clothes',
    description: 'Sophisticated 2-piece skirt and blouse sets, tailored Ankara coordinates, and contemporary luxury separates.',
    bannerImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
  },
];

export const ALL_PRODUCTS: Product[] = [
  // Gowns
  {
    id: 101,
    slug: 'ankara-infused-evening-gown',
    name: 'Ankara Infused Evening Gown',
    price: '₦45,000',
    rawPrice: 45000,
    image: '/assets/images/gowns/gown1.jpeg',
    gallery: [
      '/assets/images/gowns/gown1.jpeg',
      '/assets/images/gowns/gown2.jpeg',
      '/assets/images/gowns/gown3.jpeg',
    ],
    category: 'Gowns',
    categorySlug: 'gowns',
    badge: 'Trending',
    isNew: true,
    description: 'A showstopping evening gown blending authentic vibrant African wax prints with modern haute couture draping. Designed to flatter every silhouette effortlessly at galas, weddings, and formal occasions.',
    details: [
      'Tailored mermaid silhouette with delicate train',
      'Sweetheart neckline with reinforced internal boning',
      'High-grade Nigerian Ankara cotton & silk lining',
      'Concealed back zipper with hook-and-eye closure',
      'Dry clean only',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12', 'Custom Fitting'],
    colors: ['Emerald & Gold Wax', 'Royal Blue & Crimson'],
    fabric: 'Authentic Ankara Wax Print & Silk Chiffon',
  },
  {
    id: 102,
    slug: 'elegant-lace-overlay-gown',
    name: 'Elegant Lace Overlay Gown',
    price: '₦65,000',
    rawPrice: 65000,
    image: '/assets/images/gowns/gown2.jpeg',
    gallery: [
      '/assets/images/gowns/gown2.jpeg',
      '/assets/images/gowns/gown1.jpeg',
      '/assets/images/gowns/gown3.jpeg',
    ],
    category: 'Gowns',
    categorySlug: 'gowns',
    badge: 'Bestseller',
    isNew: true,
    description: 'Crafted with exquisite French cordonnet lace with shimmering metallic threads. This piece exudes opulence and grandeur for regal celebrations.',
    details: [
      'Hand-beaded lace overlay with subtle crystal sheen',
      'Fitted corset bodice with structured cups',
      'Floor-sweeping flared hem with horsehair trim',
      'Includes matching detachable sheer cape',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12', 'Custom Fitting'],
    colors: ['Champagne Gold', 'Rose Quartz'],
    fabric: 'Premium French Cord Lace & Duchess Satin',
  },
  {
    id: 103,
    slug: 'sleek-silk-statement-gown',
    name: 'Sleek Silk Statement Gown',
    price: '₦55,000',
    rawPrice: 55000,
    image: '/assets/images/gowns/gown3.jpeg',
    gallery: [
      '/assets/images/gowns/gown3.jpeg',
      '/assets/images/gowns/gown1.jpeg',
      '/assets/images/gowns/gown2.jpeg',
    ],
    category: 'Gowns',
    categorySlug: 'gowns',
    badge: 'Popular',
    isNew: true,
    description: 'Minimalist luxury at its finest. Cut on the bias from liquid silk charmeuse that gently hugs your contours and radiates modern sophistication.',
    details: [
      'Bias-cut body skimming silhouette',
      'Draped cowl neckline with delicate spaghetti straps',
      'Side thigh-high slit for ease of movement',
      'Fully lined in pure silk crepe',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12'],
    colors: ['Onyx Black', 'Rich Emerald', 'Tuscan Gold'],
    fabric: '100% Pure Silk Charmeuse',
  },
  {
    id: 104,
    slug: 'royal-chiffon-mermaid-gown',
    name: 'Royal Chiffon Mermaid Gown',
    price: '₦75,000',
    rawPrice: 75000,
    image: '/assets/images/gowns/gown1.jpeg',
    gallery: [
      '/assets/images/gowns/gown1.jpeg',
      '/assets/images/gowns/gown3.jpeg',
    ],
    category: 'Gowns',
    categorySlug: 'gowns',
    badge: 'Luxury',
    description: 'An architectural masterpiece featuring cascading chiffon godets and tailored bodice detailing created for the ultimate red-carpet entrance.',
    details: [
      'Mermaid cut with cascading godet inserts',
      'Off-shoulder bardot neckline',
      'Hand-finished hemline',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'Custom Fitting'],
    colors: ['Royal Gold', 'Ruby Wine'],
    fabric: 'Tiered Silk Chiffon',
  },
  {
    id: 105,
    slug: 'aso-ebi-velvet-corset-gown',
    name: 'Aso-Ebi Velvet Corset Gown',
    price: '₦85,000',
    rawPrice: 85000,
    image: '/assets/images/gowns/gown2.jpeg',
    category: 'Gowns',
    categorySlug: 'gowns',
    description: 'Plush stretch velvet combined with sheer illusion mesh panels and hand-placed beadwork. The pinnacle of modern Nigerian festive glamour.',
    details: [
      'Illusion neckline with hand-sewn glass crystal beads',
      'Built-in waist cincher corset',
      'Dramatic fishtail flare',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12'],
    colors: ['Midnight Velvet', 'Wine Burgundy'],
    fabric: 'Stretch Micro-Velvet & Crystal Mesh',
  },
  {
    id: 106,
    slug: 'pleated-satin-dinner-dress',
    name: 'Pleated Satin Dinner Dress',
    price: '₦48,000',
    rawPrice: 48000,
    image: '/assets/images/gowns/gown3.jpeg',
    category: 'Gowns',
    categorySlug: 'gowns',
    description: 'A versatile midi-to-maxi dinner gown with sunburst accordion pleating that catches the light with every step.',
    details: [
      'Micro-accordion pleated skirt',
      'Wrap bodice with tie waist sash',
      'Cap sleeves with gold accent hardware',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10'],
    colors: ['Warm Champagne', 'Forest Green'],
    fabric: 'Heavy Satin Crepe',
  },

  // Shoes
  {
    id: 201,
    slug: 'suede-pointed-mules',
    name: 'Suede Pointed Mules',
    price: '₦150,000',
    rawPrice: 150000,
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800&auto=format&fit=crop',
    category: 'Shoes',
    categorySlug: 'shoes',
    badge: 'Bestseller',
    description: 'Supple Italian suede mules shaped with a razor-sharp pointed toe and architectural block heel. Perfect for styling with gowns or tailored 2-piece sets.',
    details: [
      'Heel height: 75mm / 3 inches',
      'Pointed closed toe silhouette',
      'Padded memory foam insole for all-day comfort',
      'Handcrafted genuine leather sole',
    ],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Onyx Black', 'Warm Taupe', 'Tan'],
    fabric: '100% Genuine Italian Calf Suede',
  },
  {
    id: 202,
    slug: 'crystal-embellished-block-heels',
    name: 'Crystal Embellished Block Heels',
    price: '₦125,000',
    rawPrice: 125000,
    image: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=800&auto=format&fit=crop',
    category: 'Shoes',
    categorySlug: 'shoes',
    badge: 'Luxury',
    description: 'Statement occasion heels adorned with light-catching crystal clusters across the toe strap and stable block heel for celebratory events.',
    details: [
      'Heel height: 85mm / 3.3 inches',
      'Secure adjustable ankle strap with gold buckle',
      'Anti-slip leather outsole',
    ],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Gold Metallic', 'Silver Crystal'],
    fabric: 'Metallic Leather & Swarovski Crystal Accents',
  },
  {
    id: 203,
    slug: 'classic-pointed-leather-pumps',
    name: 'Classic Pointed Leather Pumps',
    price: '₦110,000',
    rawPrice: 110000,
    image: 'https://images.unsplash.com/photo-1596704017254-9b121068fb31?q=80&w=800&auto=format&fit=crop',
    category: 'Shoes',
    categorySlug: 'shoes',
    description: 'The quintessential power pump. Crafted from full-grain box calf leather with a sculpted stiletto heel.',
    details: [
      'Heel height: 90mm / 3.5 inches',
      'Timeless low-cut vamp',
      'Cushioned footbed',
    ],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Nude', 'Classic Black'],
    fabric: 'Full-Grain Box Calf Leather',
  },
  {
    id: 204,
    slug: 'metallic-gold-stiletto-heels',
    name: 'Metallic Gold Stiletto Heels',
    price: '₦140,000',
    rawPrice: 140000,
    image: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop',
    category: 'Shoes',
    categorySlug: 'shoes',
    isNew: true,
    description: 'Dazzling mirror-finish gold stilettos with delicate micro-straps. The ultimate party statement.',
    details: [
      'Heel height: 100mm / 4 inches',
      'Mirror metallic finish',
      'Reinforced steel heel pin',
    ],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7'],
    colors: ['Mirror Gold', 'Rose Gold'],
    fabric: 'Specchio Metallic Leather',
  },

  // Sandals
  {
    id: 301,
    slug: 'braided-gold-strap-sandals',
    name: 'Braided Gold Strap Sandals',
    price: '₦68,000',
    rawPrice: 68000,
    image: 'https://images.unsplash.com/photo-1603487742131-4160ec999306?q=80&w=800&auto=format&fit=crop',
    category: 'Sandals',
    categorySlug: 'sandals',
    badge: 'Popular',
    description: 'Hand-braided metallic leather straps weave across the foot in an effortless, elevated flat sandal designed for warm days and resort wear.',
    details: [
      'Flat heel: 10mm',
      'Hand-woven tubular leather cords',
      'Flexible leather sole',
    ],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Gold Gilt', 'Bronze'],
    fabric: 'Soft Nappa Leather',
  },
  {
    id: 302,
    slug: 'evening-ankle-strap-sandals',
    name: 'Evening Ankle Strap Sandals',
    price: '₦85,000',
    rawPrice: 85000,
    image: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=800&auto=format&fit=crop',
    category: 'Sandals',
    categorySlug: 'sandals',
    description: 'Minimalist two-strap stiletto sandals engineered for flawless posture and high comfort on the dance floor.',
    details: [
      'Heel height: 80mm',
      'Minimal front strap & ankle buckle',
    ],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7'],
    colors: ['Gold', 'Black Leather'],
    fabric: 'Patent Calf Leather',
  },
  {
    id: 303,
    slug: 'artisanal-woven-flat-sandals',
    name: 'Artisanal Woven Flat Sandals',
    price: '₦45,000',
    rawPrice: 45000,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    category: 'Sandals',
    categorySlug: 'sandals',
    description: 'Handcrafted by local leather artisans with durable hand-stitched edging and textured weave patterns.',
    details: ['Genuine cowhide footbed', 'Slip-on open toe design'],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Tan Brown', 'Honey Camel'],
    fabric: 'Vegetable-Tanned Cowhide Leather',
  },
  {
    id: 304,
    slug: 'crystal-embellished-slides',
    name: 'Crystal Embellished Slides',
    price: '₦72,000',
    rawPrice: 72000,
    image: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?q=80&w=800&auto=format&fit=crop',
    category: 'Sandals',
    categorySlug: 'sandals',
    isNew: true,
    description: 'Effortless slip-on slide sandals featuring a wide crystal-studded strap that glimmers under direct light.',
    details: ['Cushioned leather footbed', 'Easy slip-on styling'],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7'],
    colors: ['Champagne Sparkle', 'Black Crystal'],
    fabric: 'Satin & Beaded Crystals',
  },

  // Slippers
  {
    id: 401,
    slug: 'embroidered-velvet-mules',
    name: 'Embroidered Velvet Mules',
    price: '₦52,000',
    rawPrice: 52000,
    image: 'https://images.unsplash.com/photo-1588661661153-dfbc227582b6?q=80&w=800&auto=format&fit=crop',
    category: 'Slippers',
    categorySlug: 'slippers',
    badge: 'Bestseller',
    description: 'Plush velvet slide mules detailed with gold bullion wire embroidery. Delivers regal ease for lounging or casual luxury outings.',
    details: ['Quilted satin insole', 'Gold hand-embroidered crest motif', 'Non-slip outdoor rubber sole'],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Royal Emerald', 'Burgundy Wine', 'Jet Black'],
    fabric: 'Cotton Velvet & Gold Bullion Thread',
  },
  {
    id: 402,
    slug: 'hand-stitched-leather-slides',
    name: 'Hand-Stitched Leather Slides',
    price: '₦38,000',
    rawPrice: 38000,
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=800&auto=format&fit=crop',
    category: 'Slippers',
    categorySlug: 'slippers',
    description: 'Ergonomically contoured leather slide with cross-strap stitching made from buttery soft Nigerian leather.',
    details: ['Molded footbed for arch support', 'Heavy duty contrast stitching'],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7', 'EU 41 / UK 8'],
    colors: ['Chestnut Tan', 'Ebony Black'],
    fabric: 'Full-Grain Soft Cowhide',
  },
  {
    id: 403,
    slug: 'gold-monogram-house-slippers',
    name: 'Gold Monogram House Slippers',
    price: '₦45,000',
    rawPrice: 45000,
    image: 'https://images.unsplash.com/photo-1588661661153-dfbc227582b6?q=80&w=800&auto=format&fit=crop',
    category: 'Slippers',
    categorySlug: 'slippers',
    isNew: true,
    description: 'Plush monogrammed loungewear slippers embossed with the signature T&D crest in gold foil.',
    details: ['Faux fur lining for cloud-like warmth', 'Memory foam inner core'],
    sizes: ['EU 37 / UK 4', 'EU 38 / UK 5', 'EU 39 / UK 6', 'EU 40 / UK 7'],
    colors: ['Ivory Cream', 'Onyx Black'],
    fabric: 'Plush Microfiber & Faux Fur',
  },

  // Handbags
  {
    id: 501,
    slug: 'classic-leather-tote',
    name: 'Classic Leather Tote',
    price: '₦250,000',
    rawPrice: 250000,
    image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=800&auto=format&fit=crop',
    category: 'Handbags',
    categorySlug: 'handbags',
    badge: 'Bestseller',
    description: 'An expansive everyday tote crafted from textured grain leather with room for a 14-inch laptop, daily essentials, and travel gear.',
    details: [
      'Dimensions: 38cm W x 28cm H x 14cm D',
      'Reinforced dual shoulder straps',
      'Internal zippered divider pocket and key leash',
      'Protective metal feet at base',
    ],
    sizes: ['One Size'],
    colors: ['Cognac Tan', 'Midnight Black', 'Burgundy'],
    fabric: '100% Genuine Grain Calfskin',
  },
  {
    id: 502,
    slug: 'minimalist-crossbody-bag',
    name: 'Minimalist Crossbody Bag',
    price: '₦120,000',
    rawPrice: 120000,
    image: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=800&auto=format&fit=crop',
    category: 'Handbags',
    categorySlug: 'handbags',
    description: 'Clean geometric lines with an adjustable strap that converts effortlessly from day crossbody to evening shoulder bag.',
    details: [
      'Dimensions: 22cm W x 16cm H x 7cm D',
      'Magnetic flap closure with brushed gold clasp',
      'Back exterior card pocket',
    ],
    sizes: ['One Size'],
    colors: ['Ivory Butter', 'Classic Black', 'Forest Green'],
    fabric: 'Smooth Nappa Leather',
  },
  {
    id: 503,
    slug: 'gold-chain-evening-clutch',
    name: 'Gold Chain Evening Clutch',
    price: '₦95,000',
    rawPrice: 95000,
    image: 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=800&auto=format&fit=crop',
    category: 'Handbags',
    categorySlug: 'handbags',
    badge: 'Luxury',
    description: 'A hard-case minaudière evening clutch wrapped in satin with a detachable heavy link gold chain.',
    details: [
      'Dimensions: 19cm W x 11cm H x 5cm D',
      'Fits iPhone Pro Max and makeup essentials',
      'Detachable 110cm gold chain strap',
    ],
    sizes: ['One Size'],
    colors: ['Polished Gold', 'Emerald Satin'],
    fabric: 'Satin & 18k Gold Plated Brass Hardware',
  },
  {
    id: 504,
    slug: 'structured-top-handle-satchel',
    name: 'Structured Top-Handle Satchel',
    price: '₦180,000',
    rawPrice: 180000,
    image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?q=80&w=800&auto=format&fit=crop',
    category: 'Handbags',
    categorySlug: 'handbags',
    isNew: true,
    description: 'Refined structured silhouette with a rolled top handle and signature twist-lock closure.',
    details: ['Dimensions: 28cm W x 20cm H x 10cm D', 'Includes detachable shoulder strap'],
    sizes: ['One Size'],
    colors: ['Taupe Grey', 'Noir Black'],
    fabric: 'Saffiano Leather',
  },

  // Clothes (Skirts & Blouses)
  {
    id: 601,
    slug: 'adire-wrap-blouse-peplum-skirt',
    name: 'Adire Wrap Blouse & Peplum Skirt',
    price: '₦65,000',
    rawPrice: 65000,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    category: 'Clothes',
    categorySlug: 'clothes',
    badge: 'Trending',
    description: 'A striking 2-piece ensemble crafted from authentic hand-dyed Nigerian Adire silk. Features an asymmetrical wrap peplum top paired with a tailored pencil skirt.',
    details: [
      'Includes wrap peplum blouse and high-waist pencil skirt',
      'Authentic hand-dyed Indigo Adire patterns',
      'Blouse features adjustable inner and outer tie sash',
      'Skirt with rear center slit and invisible zipper',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12', 'Custom Fitting'],
    colors: ['Indigo & Cobalt Blue', 'Terracotta & Gold'],
    fabric: 'Hand-Dyed Adire Silk & Cotton Blend',
  },
  {
    id: 602,
    slug: 'tailored-silk-2-piece-set',
    name: 'Tailored Silk 2-Piece Set',
    price: '₦80,000',
    rawPrice: 80000,
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
    category: 'Clothes',
    categorySlug: 'clothes',
    badge: 'Bestseller',
    description: 'Impeccably tailored silk separates consisting of a kimono-inspired blouse and matching wide-leg trousers / maxi skirt.',
    details: ['Relaxed tailored fit', 'Mother-of-pearl buttons', 'Elasticated back waistband'],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12'],
    colors: ['Oatmeal Cream', 'Sage Green'],
    fabric: 'Heavy Raw Silk',
  },
  {
    id: 603,
    slug: 'pleated-high-waist-maxi-skirt',
    name: 'Pleated High-Waist Maxi Skirt',
    price: '₦42,000',
    rawPrice: 42000,
    image: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=800&auto=format&fit=crop',
    category: 'Clothes',
    categorySlug: 'clothes',
    description: 'Graceful high-waist maxi skirt with permanent knife pleating that billows beautifully as you walk.',
    details: ['Broad waistband with side zip', 'Full maxi length: 110cm', 'Fully lined'],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10'],
    colors: ['Mustard Gold', 'Rust Orange', 'Black'],
    fabric: 'Textured Poly-Crepe',
  },
  {
    id: 604,
    slug: 'organza-balloon-sleeve-blouse',
    name: 'Organza Balloon-Sleeve Blouse',
    price: '₦48,000',
    rawPrice: 48000,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=800&auto=format&fit=crop',
    ],
    category: 'Clothes',
    categorySlug: 'clothes',
    isNew: true,
    description: 'Dramatic sheer silk organza blouse featuring voluminous lantern sleeves and structured collar detail.',
    details: [
      'Comes with matching opaque silk camisole',
      'Extended cuffs with covered button closures',
      'French seam construction throughout',
      'Dry clean or delicate hand wash',
    ],
    sizes: ['UK 8 / US 4', 'UK 10 / US 6', 'UK 12 / US 8', 'UK 14 / US 10', 'UK 16 / US 12'],
    colors: ['Ivory Sheer', 'Bronze Glow', 'Onyx Black'],
    fabric: '100% Pure Silk Organza',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  const normalized = slug.toLowerCase();
  return ALL_PRODUCTS.find(
    (p) =>
      p.slug.toLowerCase() === normalized ||
      p.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') === normalized
  );
}
